apiVersion: batch/v1
kind: CronJob
metadata:
  name: aws-ecr-cronjob
spec:
  schedule: "30 */8 * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: aws-ecr-service-account
          containers:
          - name: aws-ecr-repository
            image: ridvanduran/aws-kubectl:latest
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: aws-secret
              - configMapRef:
                  name: aws-configmap
            command:
              - /bin/sh
              - -c
              - |-
                ECR_TOKEN=`aws ecr get-login-password --region ${AWS_REGION}`
                kubectl delete secret --ignore-not-found $DOCKER_SECRET_NAME
                kubectl create secret docker-registry $DOCKER_SECRET_NAME \
                --docker-server=https://${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com \
                --docker-username=AWS \
                --docker-password="${ECR_TOKEN}"
                echo "Secret was successfully updated at $(date)"
          restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-ecr-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-ecr-role-full-access-to-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["aws-ecr-secret"]
  verbs: ["delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aws-ecr-role-binding
subjects:
- kind: ServiceAccount
  name: aws-ecr-service-account
  apiGroup: ""
roleRef:
  kind: Role
  name: aws-ecr-role-full-access-to-secrets
  apiGroup: ""
---